apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile.yaml: |
    .:53 {
        errors
        health
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts /etc/coredns/NodeHosts {
          ttl 60
          reload 15s
          fallthrough
        }
        prometheus :9153
        forward . dns://10.2.0.1
        cache 30
        loop
        reload
        loadbalance
    }
  # this is automaintained in k3s- shouldn't need it here
  NodeHosts: |
    10.5.0.14 garage
    10.5.0.6 slash
    10.5.0.1 bang
    10.5.0.17 frontbed
    10.5.0.5 dash
